/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f1xx.h"
GPIO_TypeDef volatile *pPc13;
void config_pc13();
void EXTI15_10_IRQHandler();



int main(void)
{
	pPc13=GPIOC;
	config_pc13();
	GPIOC->ODR|= GPIO_ODR_ODR13;

    /* Loop forever */
	for(;;);

}
void config_pc13(void){
	RCC->CR|=RCC_CR_HSEON;
	RCC->APB2ENR|=RCC_APB2ENR_IOPCEN;
	RCC->APB2ENR|=RCC_APB2ENR_AFIOEN;
	GPIOC->CRH &= ~GPIO_CRH_CNF13;
	GPIOC->CRH |= GPIO_CRH_MODE13;

	RCC->APB2ENR|=RCC_APB2ENR_IOPBEN;
	//ngat tai pin a0
//	  uint32_t volatile *pAfioGpioA0=(uint32_t *)0x40010008;
//	  *pAfioGpioA0 |= (0x1<<0);
	 AFIO->EXTICR[3] |= AFIO_EXTICR4_EXTI14_PC;
	 AFIO->EXTICR[3] |= AFIO_EXTICR4_EXTI15_PC;

	 EXTI->IMR |= EXTI_IMR_IM14;
	 EXTI->RTSR |= EXTI_RTSR_RT14;

	 EXTI->IMR |= EXTI_IMR_IM15;
	 EXTI->RTSR |= EXTI_RTSR_RT15;
//	//bat mask ngat
//	  uint32_t volatile *pExti=(uint32_t *)0x40010400;
//	  *pExti|=(0x1<<15);
//	 //ringsing edge
//	  uint32_t volatile *pExtiRising=(uint32_t *)0x40010408;
//	  *pExtiRising|=(0x1<<15);

	//bat uutien ngat
	  NVIC_SetPriority(EXTI15_10_IRQn ,1);
	 //bat ngat
	  NVIC_EnableIRQ(EXTI15_10_IRQn );


}

void EXTI15_10_IRQHandler(void){
	if(EXTI->PR & (0x1<<14)){
			EXTI->PR |=(0x1<<14);
			GPIOC->ODR &= ~(0x1<<13);

		}

	if(EXTI->PR & (0x1<<15)){
				EXTI->PR |=(0x1<<15);
				GPIOC->ODR |= (0x1<<13);

			}
}
